import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import FloatingNav from "@/components/FloatingNav";
import LenisProvider from "@/components/LenisProvider";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import "./globals.css";
import "../styles/main.scss";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} h-full antialiased`}
    >
      <body className="relative min-h-full">
        <LenisProvider />
        <Header />
        <div className="grid-overlay" aria-hidden />
        <div className="dots-overlay" aria-hidden />
        <div className="relative z-10 flex min-h-full flex-col">
          {children}
          <Footer />
        </div>
        <FloatingNav />
      </body>
    </html>
  );
}
